Feat: add no-setter-return
RDambrosio016/RSLint pull request #9
Opened 2020-09-26 09:55 UTC by magurotuna

This PR adds `no-setter-return` rule, requested in #4 

Please merge this PR  _after_ #6, because some test cases cannot be passed without #6.

2020-09-26 10:01 UTC, magurotuna commented on xtask/src/docgen/extract.rs
> +
This change is related to #5, required to run `cargo xtask docgen` on `rule_test!` containing trailing comma.

2020-09-26 17:06 UTC, RDambrosio016 requested changes
Thank you for the PR!
Looks good to me except for a few minor nitpicks

2020-09-26 17:06 UTC, RDambrosio016 commented on rslint_core/src/groups/errors/no_setter_return.rs
> +                    "Setter properties are not allowed to return values, but `{}` does.",
```suggestion
                    "setter properties are not allowed to return values, but `{}` does.",
```
Error messages should be lowercase

2020-09-26 17:06 UTC, RDambrosio016 commented on rslint_core/src/groups/errors/no_setter_return.rs
> +                    "Setter properties are not allowed to return values, but `{}` does.",
The error also needs to include a primary label to the error to help the user find out where it is and to be consistent

2020-09-26 17:06 UTC, RDambrosio016 commented on xtask/src/docgen/extract.rs
> +        // If there is a trailing comma, consumes it.
```suggestion
        // if there is a trailing comma, consume it.
```
Small nit

2020-09-27 02:35 UTC, magurotuna commented
@RDambrosio016 thanks for the detailed review! Addressed all the points. Please check again :)

2020-09-27 03:03 UTC, RDambrosio016 commented
Looks good to me!

2020-09-27 03:03 UTC, merged